version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
    command: sh -c "npm start"
    expose:
      - "3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    command: sh -c "cd backend && daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://postgres:password@db:5432/train_reservations
      - REDIS_HOST=redis  # Dodajemy zmienną środowiskową dla Redis
    depends_on:
      - db
      - redis  # Dodajemy zależność na Redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: train_reservations
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"

volumes:
  db_data:
